default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: root
  password: 

development:
  <<: *default
  database: digit
  port: 33061

test:
  <<: *default
  database: digit_test

production:
  <<: *default
  database: digit_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
