default: &default
  adapter: postgresql
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  timeout: 5000

development:
  <<: *default
  database: digitsoundsystem

test:
  <<: *default
  database: digitsoundsystem_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
